# Generated by Django 3.1.7 on 2021-03-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=27)),
                ('LastName', models.CharField(max_length=27)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.IntegerField()),
            ],
        ),
    ]
