# Generated by Django 3.1.7 on 2021-03-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27, null=True, unique=True)),
                ('model', models.CharField(max_length=27)),
                ('make', models.CharField(max_length=27, null=True)),
                ('makeYear', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userName', models.CharField(max_length=27, unique=True, verbose_name='Username')),
                ('email', models.CharField(max_length=27, unique=True, verbose_name='Email Address')),
                ('firstName', models.CharField(max_length=27, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=27, null=True, verbose_name='Last Name')),
                ('mobileNumber', models.CharField(max_length=27, unique=True, verbose_name='Mobile Number')),
                ('driverLicense', models.CharField(max_length=27, null=True, unique=True, verbose_name='Driver License')),
                ('licenseValidFrom', models.DateField(null=True, verbose_name='License Validity Date')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carColor', models.CharField(max_length=27)),
                ('carRegisteration', models.CharField(max_length=27)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
