# Generated by Django 3.1.7 on 2021-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driverLicense',
            field=models.CharField(blank=True, max_length=27, null=True, unique=True, verbose_name='Driver License'),
        ),
        migrations.AlterField(
            model_name='user',
            name='licenseValidFrom',
            field=models.DateField(blank=True, null=True, verbose_name='License Validity Date'),
        ),
    ]
