# Generated by Django 3.1.7 on 2021-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Car',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
