# Generated by Django 3.1.7 on 2021-03-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210304_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
