# Generated by Django 3.1.7 on 2021-03-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210304_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=27)),
                ('MaxSeating', models.IntegerField()),
                ('LicenseNumber', models.CharField(max_length=27)),
                ('YearsUsed', models.IntegerField()),
                ('Mileage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.car'),
        ),
    ]
