# Generated by Django 3.1.7 on 2021-03-05 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210305_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Brand',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='MobileNumber',
            new_name='mobileNumber',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='car',
            name='LicenseNumber',
        ),
        migrations.RemoveField(
            model_name='car',
            name='MaxSeating',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='YearsUsed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Car',
        ),
        migrations.AddField(
            model_name='car',
            name='makeYear',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driverLicense',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='licenseValidFrom',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carColor', models.CharField(max_length=27)),
                ('carRegisteration', models.CharField(max_length=27)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
