# Generated by Django 3.1.7 on 2021-03-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210305_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=27, null=True),
        ),
    ]
