# Generated by Django 3.1.7 on 2021-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
    ]
