# Generated by Django 3.1.7 on 2021-03-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_auto_20210304_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartingPoint', models.CharField(max_length=25)),
                ('Passenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
