# Generated by Django 3.1.7 on 2021-03-04 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210304_2120'),
        ('Travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='Passenger',
        ),
        migrations.AddField(
            model_name='travels',
            name='Driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Driver_type', to='User.user'),
        ),
        migrations.AddField(
            model_name='travels',
            name='EndingPoint',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='travels',
            name='Passenger1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger1_type', to='User.user'),
        ),
        migrations.AddField(
            model_name='travels',
            name='Passenger2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger2_type', to='User.user'),
        ),
        migrations.AddField(
            model_name='travels',
            name='Price',
            field=models.IntegerField(default=1),
        ),
    ]
