# Generated by Django 3.1.7 on 2021-03-26 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0002_auto_20210323_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='createdOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
