# Generated by Django 3.1.7 on 2021-03-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0003_auto_20210326_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endingPoint',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(),
        ),
    ]
