# Generated by Django 3.1.7 on 2021-03-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210305_1027'),
        ('Travels', '0005_auto_20210305_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='Passenger3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger3_type', to='User.user'),
        ),
        migrations.AddField(
            model_name='travels',
            name='Passenger4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Passenger4_type', to='User.user'),
        ),
    ]
