# Generated by Django 3.1.7 on 2021-03-05 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Travels', '0006_auto_20210305_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travels',
            old_name='Date',
            new_name='StartDate',
        ),
        migrations.AddField(
            model_name='travels',
            name='EndDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
