# Generated by Django 3.1.7 on 2021-03-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20210305_1027'),
        ('Travels', '0008_auto_20210305_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travels',
            new_name='Ride',
        ),
    ]
